singleQuote: true
printWidth: 100
trailingComma: es5
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - '^react$'
  - '^react-dom$'
  - '^\./(AppEnvContext|GlobalThemeProvider)(/.*)?$'
  - '^(?!react$)(?!react-dom$)(?!.*\.(css|scss|sass)$)@?\\w'
  - '^@toolbox/(.*)$'
  - '^@renderer/(.*)$'
  - '^\.\./GlobalUI/.*$'
  - '^\.\./Components/.*$'
  - '^\.\./(?!GlobalUI|Components).*$'
  - '^\./(?!.*\.(css|scss|sass)$).*$'
  - '^.+\.(css|scss|sass)$'
importOrderSeparation: true
importOrderSortSpecifiers: true
